### ISSUE TITLE
Protocol format incompatibility

### ISSUE THREAD

**Issue by cboulay** [sccn/liblsl#134]
https://github.com/sccn/liblsl/commit/6e0070c2e8907e34458755d4b10a75a455374ba0 breaks protocol compatibility. @tstenner how do you want to handle it?

```
6e0070c2e8907e34458755d4b10a75a455374ba0 is the first bad commit
commit 6e0070c2e8907e34458755d4b10a75a455374ba0
Author: Tristan Stenner <ttstenner@gmail.com>
Date:   Fri Jun 7 08:24:44 2019 +0200

    Update asio subset

:040000 040000 39d4bf75bdc226466299f6df05dac297b8e73870 52e7d51da256004591a3646530404321c4ed8741 M      lslboost
:100755 100755 5b7ab2c571b9878821a1ef21d4d08ea7f49f58d0 11674ff2e70ca1a7cad43888dc25a78205cd08a8 M      update_lslboost.sh
```

**Comment by tstenner** [comment]
The good news: asio is not to blame, and neither are the 337826 changed lines in 6e0070c2e8907e34458755d4b10a75a455374ba0.
The bad news: the bug was introduced in and affects all streams except for int8-streams.
I introduced it in e9d852d128d6a1486532f2ef27b3b8c253da3d40, a commit with the fix is currently being checked in the CI, because MSVC is a bit pickier with constexpr functions than I expected.

From what I've recently read Github Actions can run a container in the background, so I'll push the "run tests against an older release" item a bit higher on my TODO list.
