### ISSUE TITLE
Provide vcpkg package for Windows

### ISSUE THREAD

**Issue by chausner** [sccn/liblsl#20]
[vcpkg](https://github.com/Microsoft/vcpkg) is a package manager that greatly facilitates building and installing C++ libraries on Windows. Providing a package for liblsl should be relatively easy as both vcpkg and liblsl are based on CMake. I started by forking the vcpkg repo and adding a [preliminary package definition](https://github.com/chausner/vcpkg/commit/7541091eeda4bc2d826c0807c155427ad47d57c1) for the latest beta release 1.13-b4. I am currently testing it and, if successful, will submit a PR to the main vcpkg repo.

vcpkg intends packages to be installable as either shared or static libraries. I encountered some issues while trying to add support for the latter which is why it's currently disabled in my fork. In particular, the current CMakeList.txt in liblsl only installs the shared target but not the static one. I would welcome changes in liblsl that provide better support for both shared and static targets as this would make it easier for me to adapt it for vcpkg. Also, please let me know if anybody has already worked on this or wants to help.

**Comment by tstenner** [comment]
That looks great, and I'm all for making it easier to get started. If there's anything I can do to help, just let me know.

Two comments from my side:

I haven't tested it (or worked with vcpkg for that matter), but the patch to CMakeLists.txt shouldn't be needed if vcpkg uses git to check out the repository. Of course, if it just downloads a tagged archive this doesn't work, but rather than the patch in the package I'd replace the `if(GIT_FOUND)` with something like
``` cmake
if(lslgitrevision AND lslgitbranch)
	message(STATUS "Got git information ${lslgitrevision}/${lslgitbranch} from the command line")
elseif(GIT_FOUND)
```
and add `set(LSLGITVER "1.13.0-b4")` and `-Dlslgitrevision=${LSLGITVER} -Dlslgitbranch=master` to `vcpkg_configure_cmake`.

Re static builds: there are some showstoppers at the moment, but they will mostly resolve themselves as soon as we bump the minimum required CMake version and reduce the dependency on embedded Boost libraries. Still, I think a shared library is a better fit for liblsl because most apps need to bundle additional libs (e.g. Qt) anyway and it might be desirable to switch out liblsl without recompiling (e.g. with a debug build with additional log output).

**Comment by chausner** [comment]
Thanks Tristan. Unfortunately, the patch appears to be necessary as vcpkg doesn't clone the repository. Even worse, the temporary build folder is located within the vcpkg distribution which itself is usually cloned from GitHub. So the commands used to retrieve commit information would probably return the completely wrong information.

I agree with your other suggestion regarding the patch and will be integrating it.

Based on your comment I'll keep static builds disabled for now and may add support for them in a later liblsl release when there is proper support for it.

**Comment by tstenner** [comment]
> I agree with your other suggestion regarding the patch and will be integrating it.

Great, just send in a PR and I'll merge it before the final 1.13 release.

**Comment by tstenner** [comment]
I've incorporated your changes and tagged a new release.

**Comment by chausner** [comment]
Great, thanks! I'll update the port in vcpkg to use the latest version which will maks the patches obsolete.

**Comment by chausner** [comment]
The changes have been [accepted in vcpkg](https://github.com/microsoft/vcpkg/pull/6745). I'll close this issue as the only remaining task is better support for static builds, and this seems part of #15 already.
