### ISSUE TITLE
Linking via qMake lsl.lib vs liblsl64.lib

### ISSUE THREAD

**Issue by LorenzE** [sccn/liblsl#65]
I am trying to link against the lsl lib via qmake, see [here](https://github.com/LorenzE/mne-cpp/blob/de895bdde60223465b19f4b9c1a60273a7774b54/applications/mne_scan/plugins/lsladapter/lsladapter.pro#L86). I am building on Windows 10 and downloaded liblsl-1.14.0-Win64. During compilation I get the error that linkage to `liblsl64.lib` is not possible. The pre built binaries include `lsl.lib` without the 64 or 32 keyword. I also tried building lsl from source, but all I got is `lsl.lib` and not `liblsl64.lib`. Am I missing some steps here? The [lsl_cpp.h](https://github.com/sccn/liblsl/blob/96fd7b1b48f6c938090b50bfa18f7339549fac95/include/lsl_cpp.h#L16) also states that  `liblsl32.lib` or  `liblsl64.lib` need to be linked.

**Comment by cboulay** [comment]
1.14.0 is in beta. This was intended to be indicated by the `b1` suffix on the version name. Sorry if that wasn't clear. I've since updated the GitHub release page to indicate that it is a "prerelease".

In 1.14, the `lib` prefix and `64` suffix is dropped from the Windows libraries. This is actually more consistent with standard practices in Windows (e.g., take a look at C:\Windows\System32 and see how many dlls start with 'lib' and how many have '64' as a suffix). If you require the prefix and suffix then you can build liblsl yourself with [`LSL_FORCE_FANCY_LIBNAME`](https://github.com/sccn/liblsl/blob/master/CMakeLists.txt#L18). That being said, we don't want you to have to do that and we'd like to fix this issue.

Sorry I don't use qmake much. I don't get why it is looking for `liblsl64.lib` when all you provide is `-llsl`. In the [qmake docs here](https://doc.qt.io/qt-5/third-party-libraries.html#library-files), adding `-lCatWhisperer` searchers for CatWhisperer.lib, without the lib prefix or 64 suffix. What's different? `-llibfftw3-3` isn't looking for `liblibfftw3-364.lib` is it? 

As for the text in lsl_cpp.h, yes I suppose that's a little too specific and should instead just say "the lsl libraries".

**Comment by tstenner** [comment]
> In 1.14, the lib prefix and 64 suffix is dropped from the Windows libraries.

The other reason is that for some processor+OS combinations a function parameter changed size so the libraries not having the same name prevents programs compiled against the new version to be used with older library versions.

> The lsl_cpp.h also states that liblsl32.lib or liblsl64.lib need to be linked.

Good catch, I've fixed the comment.

**Comment by LorenzE** [comment]
Thx for your help @cboulay @tstenner I got it to work with lsl.lib compiled from source. I was just not on the newest commit. A simple git pull did the trick. Sry about the noise. 

Which compiler was the pre-release 64bit asset compiled with?

**Comment by tstenner** [comment]
> Sry about the noise.

Oversight on my part, thanks for reporting it :-)

> Which compiler was the pre-release 64bit asset compiled with?

The Windows builds are currently done on [Appveyor](https://ci.appveyor.com/project/cboulay/liblsl/builds/31307699/job/gvb25n44dsywpeh2) with Visual Studio 2015. VS2015 is the oldest supported compiler for 1.14, but maybe it'd make sense to switch the release builds to VS2019.
