### ISSUE TITLE
manylinux binaries - how to make them available to python setup?

### ISSUE THREAD

**Issue by cboulay** [sccn/liblsl#78]
Sorry I can't remember what the latest status was on the manylinux shared objects necessary for pylsl.

We have an azure-pipelines file that is building them:
https://github.com/sccn/liblsl/blob/master/azure-pipelines.yml

But the .so's aren't being attached to releases. The last one to have them is 1.13.0-b13. Since then, the manylinux so's are missing from 1.13.0-b14 , 1.13.1, and the 1.14-bXXs. The latter maybe because they are 'pre-releases'. The1.13.1 maybe didn't upload because the azure build failed due to old MacOS version.

I just re-triggered a pipeline build on release 1.13.1, this failed out due to MacOS version, so I downloaded the manylinux artifacts. Edit - turns out I can upload the .so files.

I've published a new pylsl release. I hope it doesn't break anything!
https://github.com/labstreaminglayer/liblsl-Python/issues/6

**Comment by cboulay** [comment]
I can't find a good commit for 1.13.2. I'll just do the .zip thing manually for 1.13.1.

**Comment by tstenner** [comment]
Last time I checked, uploading from Azure Pipelines is a bit tricky because the config has to define whether to append artifacts to an existing release or create a new one, but in case the release isn't there the whole process will fail so we'd have to bet on Azure always being faster or slower than all other CIs. The Mac builds also suffer from the multicasting problem, but I think I still count them as successful builds.
